### ISSUE TITLE
VitorRisk branch, chapter 10: Incorrect Formula

### ISSUE THREAD

**Issue by larsbutler** [gem/openquake-book#3]
The 'Lowerbound' formula defined on page 47 is incorrect; there is a sign error.

The OQB.pdf shows:
Lowerbound = IML1 - ((IML2 + IML1) / 2)

It should be:
Lowerbound = IML1 - ((IML2 - IML1) / 2)

**Comment by daniviga** [comment]
Expired. Closing.
